### ISSUE TITLE
Dat Version example

### ISSUE THREAD

**Issue by martinheidegger** [pfrazee/parse-dat-url#2]
Probably I have found a documentation issue: I am looking at the example of the `version` and it states `v1.0.0`. To my understanding though a "version" to be checked out in dat needs to be a number:

[`this._head = typeof opts.checkout === 'number' ? opts.checkout : -1`](https://github.com/mafintosh/append-tree/blob/39b803c2a740d89d7b5f567d6ac50f6bfa0a4c4f/index.js#L21)

Should `parse-dat-url` throw an error if the version is something other than a number? At the very least I'd think to avoid confusion: it would be good to update the example to show a number?

**Comment by pfrazee** [comment]
The dat URL spec, such as it is, doesn't currently require the version to be a string. This is because we plan to integrate additional versioning schemes which support non-numbers. (In fact, Beaker currently uses two hard-coded versions, 'latest' and 'preview'.)
